datahub/api/urls.py
from django.conf.urls import url
from code_processing.api import SubmittedCodeCreateAPIView
from data_analysis.api import DatasetRetrieveAPIView, ProjectRetrieveAPIView

urlpatterns = [
    url(r'^dataset/(?P<pk>\d+)/$', DatasetRetrieveAPIView.as_view(), name="dataset"),
    url(r'^submittedcode/$', SubmittedCodeCreateAPIView.as_view(), name="code"),
    url(r'^project/(?P<pk>\d+)/$', ProjectRetrieveAPIView.as_view(), name="project")
]

datahub/data_analysis/urls.py
from django.conf.urls import url
from data_analysis.api import DatasetRetrieveAPIView
from data_analysis.views import DatasetDetailView, ProjectDetailView, ProjectCreateView, ProjectDeleteView, \
    DatasetDeleteView, dataset_query_view, ProjectCloneView
from fileupload.views import DatafileUploadView


urlpatterns = [
    url(r'^(?P<username>[-\w]+)/new_project/$', ProjectCreateView.as_view(), name="create_project"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/upload/$',
        DatafileUploadView.as_view(),
        name="upload"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/delete/$',
        ProjectDeleteView.as_view(),
        name="delete_project"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/fork/$',
        ProjectCloneView.as_view(),
        name="fork_project"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/(?P<dataset>[-\w]+)/delete/$',
        DatasetDeleteView.as_view(),
        name="dataset_detail"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/(?P<dataset>[-\w]+)/api/$',
        DatasetRetrieveAPIView.as_view(),
        name="temp_api"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/(?P<dataset>[-\w]+)/$',
        DatasetDetailView.as_view(),
        name="dataset_detail"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/$',
        ProjectDetailView.as_view(),
        name="project_detail"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/(?P<dataset>[-\w]+)/query/$',
        dataset_query_view,
        name="dataset_query"),

]

datahub/datahub/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from user_profiles.views import ProfileListView, ProfileCreateView, ProfileUpdateView, ProfileDetailView
from user_registration import urls as user_reg
from data_analysis import urls as data_analysis
from api import urls as api_url
from user_registration.views import LoginView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls), name="admin"),
    url(r'^register/', include(user_reg, namespace="register")),
    url(r'^accounts/logout/$',
        'django.contrib.auth.views.logout',
        name='logout',
        kwargs={'next_page': reverse_lazy("home")}),
    url(r'^accounts/login/$', LoginView.as_view(additional_context={"panel_title": "Please Log In", "submit_button_name": "Login"}), name="login"),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^$', ProfileListView.as_view(), name="home"),
    url(r'^new_profile/$', ProfileCreateView.as_view(), name="profile_creation"),
    url(r'^update_profile/$', ProfileUpdateView.as_view(), name="update"),
    url(r'^api/', include(api_url, namespace="api")),
    url(r'^(?P<username>[-_\w]+)/$', ProfileDetailView.as_view(), name="user_profile"),
    url(r'^', include(data_analysis, namespace="data_analysis")),
]

datahub/user_profiles/urls.py
from django.conf.urls import url
from user_profiles import views

urlpatterns = [
    url(r'^$', views.ProfileDetailView.as_view(), name="detail"),
]

datahub/user_registration/urls.py
from django.conf.urls import url
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView
from user_registration.views import RegistrationView

urlpatterns = [
    url(r'', RegistrationView.as_view(additional_context={"panel_title": "Registration", "submit_button_name": "Register"}),
        name="register"),
    url(r'k', CreateView),
]

datahub/data_analysis/models.py
from django.core.urlresolvers import reverse_lazy
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from picklefield import PickledObjectField
from datahub.helpers.validators import start_with_letter_validator, contains_only_letters_dash_underscore_validator
from user_profiles.models import Profile


class Project(models.Model):
    name = models.CharField(max_length=64,
                            validators=[start_with_letter_validator,
                                        contains_only_letters_dash_underscore_validator])
    profile = models.ForeignKey(Profile)

    class Meta:
        unique_together = ("name", "profile")

    def __str__(self):
        return "{}/{}".format(self.profile.user.username, self.name)

    @property
    def link(self):
        return reverse_lazy("data_analysis:project_detail",
                            kwargs={"username": self.profile.user.username,
                                    "project": self.name})

    def dataset_upload_link(self):
        return reverse_lazy("data_analysis:upload",
                            kwargs={"username": self.profile.user.username,
                                    "project": self.name})

    def project_fork_link(self):
        return reverse_lazy("data_analysis:fork_project",
                            kwargs={"username": self.profile.user.username,
                                    "project": self.name})



class Dataset(models.Model):
    name = models.CharField(max_length=128,
                            validators=[start_with_letter_validator,
                                        contains_only_letters_dash_underscore_validator])
    project = models.ForeignKey(Project)
    data = PickledObjectField()
    head = PickledObjectField()
    column_list = PickledObjectField()
    num_obs = models.IntegerField()
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("name", "project")

    def __str__(self):
        return "{}/{}/{}".format(self.project.profile.user.username,
                                 self.project.name,
                                 self.name)

    def as_html(self, head=True):
        if head:
            return self.head.to_html()
        return self.data.tail.to_html()

    @property
    def head_as_html(self):
        return self.as_html()

    @property
    def query_link(self):
        return reverse_lazy("data_analysis:dataset_query",
                            kwargs={"username": self.project.profile.user.username,
                                    "project": self.project.name,
                                    "dataset": self.name})

    @property
    def link(self):
        return reverse_lazy("data_analysis:dataset_detail",
                            kwargs={"username": self.project.profile.user.username,
                                    "project": self.project.name,
                                    "dataset": self.name})

    @property
    def api_link(self):
        return reverse_lazy("api:dataset",
                            kwargs={"pk": self.pk})

@receiver(pre_save, sender=Dataset)
def update_head(instance, **kwargs):
    if instance.data is not None:
        instance.head = instance.data.head(20)
        instance.column_list =instance.head.columns
        instance.num_obs = len(instance.data.index)

datahub/user_profiles/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class Profile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

datahub/user_profiles/views.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from datahub.helpers.mixins import ProvideProfileMixin, AddUserToFormMixin, LoginRequiredMixin, AddContextInAsViewMixin
from user_profiles.models import Profile


class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'user_profiles/public_profile.html'

    def get_object(self, queryset=None):
        return User.objects.get(username=self.kwargs.get("username")).profile


class ProfileListView(ListView):
    model = Profile
    template_name = 'user_profiles/profile_list.html'


class ProfileUpdateView(AddContextInAsViewMixin, ProvideProfileMixin, UpdateView):
    additional_context = {"panel_title": "Update Profile", "submit_button_name": "Update"}
    model = Profile
    template_name = 'single_form_view.html'
    fields = ['name', 'email']

    def get_success_url(self):
        return reverse_lazy("user_profile", kwargs={"username": self.request.user.username})


class ProfileCreateView(AddContextInAsViewMixin, LoginRequiredMixin, AddUserToFormMixin, CreateView):
    additional_context = {"panel_title": "Create Profile", "submit_button_name": "Create"}
    model = Profile
    template_name = 'single_form_view.html'
    fields = ['name', 'email']

    def get_success_url(self):
        return reverse_lazy("user_profile", kwargs={"username": self.request.user.username})

datahub/frontend/templates/user_profiles/profile_list.html
{% extends "base.html" %}


{% block body %}

    <div class="container">
        <h2><br/></h2>
        <!-- /.row -->
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% if not request.user.is_authenticated %}
                    <div class="row">
                        <div class="col-md-6">
                            <a href="{% url "login" %}" class="btn btn-success btn-outline">
                                Login
                            </a>
                        </div>
                        <div class="col-md-6">
                            <a href="{% url "register:register" %}" class="btn btn-success btn-outline pull-right">
                                Register
                            </a>
                        </div>
                    </div>
                    <br/>
                {% endif %}
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h2>
                                            Users
                                        </h2>
                                    </div>
                                </div>
                            </div>
                            <!-- .panel-heading -->
                            <div class="panel-body">
                                {% for object in object_list %}
                                    <h5>
                                        <a href="{% url "user_profile" username=object.user.username %}">
                                            <i class="fa fa-user"></i> <strong>{{ object.user.username }}</strong>
                                        </a>
                                    </h5>
                                    {% if not forloop.last %}
                                        <hr>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <!-- .panel-body -->
                        </div>
                    </div>
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>


{% endblock %}

datahub/frontend/templates/user_profiles/profile_update.html
{% extends "base.html" %}

{% block body %}
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="create">
        </form>
    </div>
{% endblock %}

datahub/frontend/templates/user_profiles/public_profile.html
{% extends "base.html" %}

{% block body %}
    <div class="container">
        <h2><br/></h2>
        <!-- /.row -->
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-7">
                                <h2>
                                    Projects
                                </h2>
                                <hr/>
                                {% comment No search functionality yet %}
                                <div class="form-group input-group custom-search-form">
                                    <input type="text" class="form-control" placeholder="Search...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </div>
                                {% endcomment %}
                            </div>
                            <div class="col-md-5">
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        {{ object.user.username }}
                                    </div>
                                    <div class="panel-body black-text">
                                        <p><strong>Name: </strong>{{ object.name }}</p>
                                        <p><strong>Email: </strong>{{ object.email }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- .panel-heading -->
                    <div class="panel-body">
                        {% if request.user == object.user %}
                                <h5>
                                    <a href="{% url "data_analysis:create_project" username=request.user.username %}">
                                        <i class="fa fa-plus-square-o"></i>  Start new project
                                    </a>
                                </h5>
                            <hr>
                        {% endif %}
                        {% for project in object.project_set.all %}
                                <h5>
                                    <a href="{{ project.link }}">
                                        <i class="fa fa-folder-o"></i>  {{ project.name }}
                                    </a>
                                </h5>
                            {% if not forloop.last %}
                                <hr>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <!-- .panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
{% endblock %}