datahub/api/urls.py
from django.conf.urls import url
from code_processing.api import SubmittedCodeCreateAPIView
from data_analysis.api import DatasetRetrieveAPIView, ProjectRetrieveAPIView

urlpatterns = [
    url(r'^dataset/(?P<pk>\d+)/$', DatasetRetrieveAPIView.as_view(), name="dataset"),
    url(r'^submittedcode/$', SubmittedCodeCreateAPIView.as_view(), name="code"),
    url(r'^project/(?P<pk>\d+)/$', ProjectRetrieveAPIView.as_view(), name="project")
]

datahub/data_analysis/urls.py
from django.conf.urls import url
from data_analysis.api import DatasetRetrieveAPIView
from data_analysis.views import DatasetDetailView, ProjectDetailView, ProjectCreateView, ProjectDeleteView, \
    DatasetDeleteView, dataset_query_view, ProjectCloneView
from fileupload.views import DatafileUploadView


urlpatterns = [
    url(r'^(?P<username>[-\w]+)/new_project/$', ProjectCreateView.as_view(), name="create_project"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/upload/$',
        DatafileUploadView.as_view(),
        name="upload"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/delete/$',
        ProjectDeleteView.as_view(),
        name="delete_project"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/fork/$',
        ProjectCloneView.as_view(),
        name="fork_project"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/(?P<dataset>[-\w]+)/delete/$',
        DatasetDeleteView.as_view(),
        name="dataset_detail"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/(?P<dataset>[-\w]+)/api/$',
        DatasetRetrieveAPIView.as_view(),
        name="temp_api"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/(?P<dataset>[-\w]+)/$',
        DatasetDetailView.as_view(),
        name="dataset_detail"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/$',
        ProjectDetailView.as_view(),
        name="project_detail"),

    url(r'^(?P<username>[-\w]+)/(?P<project>[-\w]+)/(?P<dataset>[-\w]+)/query/$',
        dataset_query_view,
        name="dataset_query"),

]

datahub/datahub/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from user_profiles.views import ProfileListView, ProfileCreateView, ProfileUpdateView, ProfileDetailView
from user_registration import urls as user_reg
from data_analysis import urls as data_analysis
from api import urls as api_url
from user_registration.views import LoginView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls), name="admin"),
    url(r'^register/', include(user_reg, namespace="register")),
    url(r'^accounts/logout/$',
        'django.contrib.auth.views.logout',
        name='logout',
        kwargs={'next_page': reverse_lazy("home")}),
    url(r'^accounts/login/$', LoginView.as_view(additional_context={"panel_title": "Please Log In", "submit_button_name": "Login"}), name="login"),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^$', ProfileListView.as_view(), name="home"),
    url(r'^new_profile/$', ProfileCreateView.as_view(), name="profile_creation"),
    url(r'^update_profile/$', ProfileUpdateView.as_view(), name="update"),
    url(r'^api/', include(api_url, namespace="api")),
    url(r'^(?P<username>[-_\w]+)/$', ProfileDetailView.as_view(), name="user_profile"),
    url(r'^', include(data_analysis, namespace="data_analysis")),
]

datahub/data_analysis/models.py
from django.core.urlresolvers import reverse_lazy
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from picklefield import PickledObjectField
from datahub.helpers.validators import start_with_letter_validator, contains_only_letters_dash_underscore_validator
from user_profiles.models import Profile


class Project(models.Model):
    name = models.CharField(max_length=64,
                            validators=[start_with_letter_validator,
                                        contains_only_letters_dash_underscore_validator])
    profile = models.ForeignKey(Profile)

    class Meta:
        unique_together = ("name", "profile")

    def __str__(self):
        return "{}/{}".format(self.profile.user.username, self.name)

    @property
    def link(self):
        return reverse_lazy("data_analysis:project_detail",
                            kwargs={"username": self.profile.user.username,
                                    "project": self.name})

    def dataset_upload_link(self):
        return reverse_lazy("data_analysis:upload",
                            kwargs={"username": self.profile.user.username,
                                    "project": self.name})

    def project_fork_link(self):
        return reverse_lazy("data_analysis:fork_project",
                            kwargs={"username": self.profile.user.username,
                                    "project": self.name})



class Dataset(models.Model):
    name = models.CharField(max_length=128,
                            validators=[start_with_letter_validator,
                                        contains_only_letters_dash_underscore_validator])
    project = models.ForeignKey(Project)
    data = PickledObjectField()
    head = PickledObjectField()
    column_list = PickledObjectField()
    num_obs = models.IntegerField()
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("name", "project")

    def __str__(self):
        return "{}/{}/{}".format(self.project.profile.user.username,
                                 self.project.name,
                                 self.name)

    def as_html(self, head=True):
        if head:
            return self.head.to_html()
        return self.data.tail.to_html()

    @property
    def head_as_html(self):
        return self.as_html()

    @property
    def query_link(self):
        return reverse_lazy("data_analysis:dataset_query",
                            kwargs={"username": self.project.profile.user.username,
                                    "project": self.project.name,
                                    "dataset": self.name})

    @property
    def link(self):
        return reverse_lazy("data_analysis:dataset_detail",
                            kwargs={"username": self.project.profile.user.username,
                                    "project": self.project.name,
                                    "dataset": self.name})

    @property
    def api_link(self):
        return reverse_lazy("api:dataset",
                            kwargs={"pk": self.pk})

@receiver(pre_save, sender=Dataset)
def update_head(instance, **kwargs):
    if instance.data is not None:
        instance.head = instance.data.head(20)
        instance.column_list =instance.head.columns
        instance.num_obs = len(instance.data.index)

datahub/data_analysis/forms.py
from django import forms
from data_analysis.models import Project


class ProjectForkForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ["name"]

datahub/data_analysis/views.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render_to_response
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView, FormView
from pandasql import sqldf

from code_processing.forms import CodeForm
from data_analysis.forms import ProjectForkForm
from data_analysis.models import Dataset, Project
from datahub.helpers.mixins import AddProfileToFormMixin, VerifyUserBeforeDeletionMixin, ProvideProjectFromURLMixin, \
    ProvideDatasetFromURLMixin, AddContextInAsViewMixin
from fileupload.forms import DatafileUploadForm


class DatasetListView(ListView):
    model = Dataset


class DatasetDetailView(ProvideDatasetFromURLMixin, DetailView):
    model = Dataset
    template_name = "data_analysis/dataset.html"

    def get_context_data(self, **kwargs):
        context = {"code_form": CodeForm}
        context.update(kwargs)
        return super().get_context_data(**context)


class DatasetDeleteView(ProvideDatasetFromURLMixin, VerifyUserBeforeDeletionMixin, DeleteView):
    model = Dataset

    def get_success_url(self):
        return reverse_lazy("data_analysis:project_detail",
                            kwargs={"username": self.kwargs.get("username"),
                                    "project": self.kwargs.get("project")})


class ProjectListView(ListView):
    model = Project


class ProjectDetailView(ProvideProjectFromURLMixin, DetailView):
    model = Project
    template_name = "data_analysis/project_detail.html"

    def get_context_data(self, **kwargs):
        context = {"upload_form": DatafileUploadForm}
        context.update(kwargs)
        return super().get_context_data(**context)


class ProjectDeleteView(ProvideProjectFromURLMixin, VerifyUserBeforeDeletionMixin, DeleteView):
    model = Project
    success_url = reverse_lazy("")

    def get_success_url(self):
        return reverse_lazy("user_profile", kwargs={"username": self.request.user.username})


class ProjectCreateView(AddContextInAsViewMixin, AddProfileToFormMixin, CreateView):
    model = Project
    template_name = 'single_form_view.html'
    fields = ['name']
    additional_context = {"panel_title": "Create Project",
                          "submit_button_name": "Create"}

    def get_success_url(self):
        return reverse_lazy("data_analysis:project_detail",
                            kwargs={"username": self.request.user.username,
                                    "project": self.get_form_kwargs().get("data").get("name")})


class DatasetQueryView(ProvideDatasetFromURLMixin, UpdateView):
    template_name = 'data_analysis/dataset_query.html'

    def get_context_data(self, **kwargs):
        context = {"code_form": CodeForm}
        context.update(kwargs)
        return super().get_context_data(**context)

    def post(self, request, *args, **kwargs):
        pass


def dataset_query_view(request, username, project, dataset):
    if request.POST:
        user = User.objects.get(username=username)
        project = Project.objects.get(name=project, profile=user.profile)
        dataset = Dataset.objects.get(name=dataset, project=project)
        datasets = {data.name: data.data for data in project.dataset_set.all()}
        code = request.POST.get("code")
        context = {'result': sqldf(code, datasets).head(20).to_html(),
                   'object': dataset,
                   'code': code}
        return render_to_response("data_analysis/dataset_query.html", context=context)

class ProjectCloneView(AddContextInAsViewMixin, ProvideProjectFromURLMixin, FormView):
    form_class = ProjectForkForm
    template_name = "single_form_view.html"
    additional_context = {"panel_title": "Clone Project",
                          "submit_button_name": "Clone"}

    def form_valid(self, form):
        project = self.get_object()
        project.pk = None
        project.name = form.instance.name
        project.profile = self.request.user.profile
        project.save()
        for dataset in self.get_object().dataset_set.all():
            dataset.pk = None
            dataset.project = project
            dataset.save()
            try:
                submitted_code = dataset.submittedcode
                submitted_code.pk = None
                submitted_code.project = project
                submitted_code.result = dataset
            except ObjectDoesNotExist:
                pass
        self.success_url = reverse_lazy("data_analysis:project_detail",
                                        kwargs={"username": project.profile.user.username,
                                                "project": project.name})
        return super().form_valid(form)

    def get_initial(self):
        self.initial = {"name": self.get_object().name}
        return super().get_initial()

datahub/frontend/templates/data_analysis/dataset.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block body %}
    <div id="page-wrapper">
        <br/>
        {% if request.user == object.project.profile.user %}
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        Code
                    </div>
                    <div class="panel-body">
                        <form role="form" id="code_form">
                            {% csrf_token %}
                            {% for field in code_form %}
                                {% render_field field class+="form-control" autofocus="" rows=3 %}
                            {% endfor %}
                            <input type="hidden" name="project_id" value="{{ object.project.id }}"/>
                            <br/>
                            <input class="btn btn-outline btn-success" id="submit_code" type="submit" value="run">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <br/>
        {% endif %}
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="link_pointer">
                            <a href="{{ object.project.link }}">{{ object.project.name }}</a> / <a id="dataset_link">{{ object.name }}</a>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <div class="dataTable_wrapper">
                            <div class="table-scroll">
                                <table class="table table-striped table-bordered compact" id="dataset">
                                    <thead>
                                        {% for column in object.column_list %}
                                            <th>{{ column }}</th>
                                        {% endfor %}
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 col-md-offset-10">
                <form method="post" action="{{ object.link }}delete/" id="delete_form">
                    {% csrf_token %}
                    <p><input class="btn btn-outline btn-danger" type="submit" value="delete dataset" id="delete_dataset"></p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}





{% block sidebar %}
    <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav link_pointer" id="side-menu">
                        <li>
                            <a href="{{ object.project.link }}">{{ object.project.name }} Datasets</a>
                        </li>
                        {% for project_dataset in object.project.dataset_set.all %}
                            <li>
                                <a id="load_{{ project_dataset.name }}" {% if project_dataset == object %}class="active"><strong{% endif %}><i class="fa fa-table fa-fw"></i> {{ project_dataset.name }}{% if project_dataset == object %}</strong>{% endif %}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
{% endblock %}

{% block scripts %}

    <!-- DataTables JavaScript -->
    <script src="{% static "bower_components/datatables/media/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js" %}"></script>
    <script type="application/javascript">

        var initLoad = function(table, url) {
            table.dataTable({
                ajax: url,
                responsive: true
            });
        };


        var load_datasets = function() {
            var list = $("#side-menu");
            list.empty();
            var li = $('<li></li>').attr("style", "text-align:center");
            var href = $('<a></a>').attr('href', "{{ object.project.link }}");
            var heading = $('<h4></h4>').text("{{ object.project.name }} Datasets");
            href.append(heading);
            li.append(href);
            list.append(li);
            $.ajax({
                url: "{% url "api:project" object.project.id %}",
                type: "get",
                dataType: 'json',
                success: function(response) {
                    var list = $("#side-menu");
                    for(i=0; i<response.datasets.length; i++) {
                        var name = response.datasets[i].name;
                        var li = $('<li></li>');
                        var a = $('<a></a>').attr("id", name);
                        var strong = $('<strong></strong>');
                        var icon = $('<i></i>').addClass("fa fa-table fa-fw");
                        strong.text(" "+name);
                        a.append(icon);
                        a.append(strong);
                        a.addClass("link_pointer");
                        if(name === $("#dataset").textContent) {
                            a.addClass("active");
                        }
                        a.attr('data-url', response.datasets[i].url + "?columns=1");
                        a.click({'test': 'test'}, function() {
                            $.ajax({
                                url: $(this).attr("data-url"),
                                type: "get",
                                dataType: 'json',
                                success: reload_table
                            })
                        });
                        li.append(a);
                        list.append(li);
                    }
                }
            })
        };

        var reload_table = function(response) {
                var container = $(".table-scroll");
                container.empty();
                var table = $('<table></table>').addClass('table table-striped table-bordered compact').attr('id', "test");
                var head = $('<thead></thead>');
                var row = $('<tr></tr>');
                for(i=0; i<response.columns.length; i++) {
                    var element = $('<th></th>').text(response.columns[i]);
                    row.append(element);
                }
                head.append(row);
                table.append(head);
                container.append(table);
                initLoad(table, response.url);
                $('#dataset_link').text(response.name);
                $('#delete_form').attr('action', "{{ object.project.link }}" + response.name + "/delete/");
                load_datasets();
            };

        var submit_code = function(e) {
            e.preventDefault();
            var form = $("#code_form");
            $.ajax({
                url: "{% url "api:code" %}",
                type: "post",
                dataType: 'json',
                data: form.serialize(),
                success: reload_table
            })
        };

        $('document').ready(function() {
            initLoad($("#dataset"), "{{ object.api_link }}");
            $("#submit_code").click(submit_code);
            load_datasets();
        });
    </script>

{% endblock %}

datahub/frontend/templates/data_analysis/dataset_query.html
{% extends "base.html" %}

{% block body %}
    {{ result|safe }}
{% endblock %}

datahub/frontend/templates/data_analysis/project_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h2 class="page-header"><a href="{% url "user_profile" username=object.profile.user.username %}">{{ object.profile.user.username }}</a> / <a href="{{ object.link }}">{{ object.name }}</a></h2>
            </div>
            <div class="col-md-2 pull-right">
                {% if request.user.profile %}
                    <a class="btn btn-outline btn-primary page-header" href="{{ project.project_fork_link }}"><i class="fa fa-code-fork"></i> Clone Project</a>
                {% endif %}
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3>Datasets</h3>
                    </div>
                    <!-- .panel-heading -->
                    <div class="panel-body">
                        {% if request.user == object.profile.user %}
                            <a class="btn btn-outline btn-primary" href="{{ project.dataset_upload_link }}"><i class="fa fa-upload"></i> Upload New Dataset</a>
                            <hr/>
                        {% endif %}
                        <div class="panel-group" id="accordion">
                            {% for dataset in object.dataset_set.all %}
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#{{ dataset.name }}"><i class="fa fa-table"></i> {{ dataset.name }}</a>
                                        </h4>
                                    </div>
                                    <div id="{{ dataset.name }}" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            <div class="col-md-3">
                                                <p>
                                                    <a class="btn btn-outline btn-primary btn-block" href="{{ dataset.link }}">Create Query</a>
                                                </p>
                                                <hr/>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="table-responsive">
                                                    <div class="table-scroll">
                                                        <table class="table table-striped table-bordered compact" id="dataset_{{ dataset.name }}">
                                                            <thead>
                                                                <tr>
                                                                    {% for column in dataset.column_list %}
                                                                        <th>{{ column }}</th>
                                                                    {% endfor %}
                                                                </tr>
                                                            </thead>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- .panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>
{% endblock %}



{% block scripts %}

    <!-- DataTables JavaScript -->
    <script src="{% static "bower_components/datatables/media/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js" %}"></script>
    <script type="application/javascript">

        var initLoad = function(table, url) {
            table.dataTable({
                ajax: url,
                responsive: true
            });
        };

        $('document').ready(function() {
            {% for dataset in project.dataset_set.all %}
                initLoad($("#dataset_" + "{{ dataset.name }}"), "{{ dataset.api_link }}");
            {% endfor %}
        });
    </script>

{% endblock %}